version: '3'
services:
  api:
    build:
      context: .    # Use the current directory (webstatus-be) as the build context
      dockerfile: Dockerfile    # Dockerfile is in the root directory
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
